language: node_js
node_js:
  - "8"
script:
  - npm run build --prod
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN
branches:
  only:
  - development